import type { Account, AccountStore, AlertHistory, CorrectionAlert, SavedArea } from "./types";
export const MAX_SAVED_AREAS = 25; export const MAX_CUSTOM_AREA_SQUARE_KILOMETRES = 5_000;
export const circleAreaSquareKilometres = (radiusKilometres: number) => Math.PI * radiusKilometres ** 2;
export function areasForOwner(store: AccountStore, ownerId: string): readonly SavedArea[] { return store.savedAreas.filter((area) => area.ownerId === ownerId); }
export function historyForOwner(store: AccountStore, ownerId: string): readonly AlertHistory[] { return store.alertHistory.filter((item) => item.ownerId === ownerId); }
export function addSavedArea(store: AccountStore, area: SavedArea): AccountStore { const owner = store.accounts.find((account) => account.id === area.ownerId); const radiusArea = area.radiusKilometres === undefined ? undefined : circleAreaSquareKilometres(area.radiusKilometres); if (!owner?.emailVerifiedAt) throw new Error("A verified email is required."); if (areasForOwner(store, area.ownerId).length >= MAX_SAVED_AREAS) throw new Error("Saved-area limit reached."); if (!area.geometry.trim() || !Number.isFinite(area.areaSquareKilometres ?? 0) || (area.areaSquareKilometres !== undefined && (area.areaSquareKilometres <= 0 || area.areaSquareKilometres > MAX_CUSTOM_AREA_SQUARE_KILOMETRES)) || (area.radiusKilometres !== undefined && (!Number.isFinite(area.radiusKilometres) || area.radiusKilometres <= 0 || radiusArea! > MAX_CUSTOM_AREA_SQUARE_KILOMETRES))) throw new Error("A bounded geometry or area is required."); return { ...store, savedAreas: [...store.savedAreas, area] }; }
export function requestDeletion(account: Account, requestedAt: string): Account { return { ...account, deletionRequestedAt: requestedAt }; }
export function unsubscribeWithToken(account: Account, token: string, unsubscribedAt: string): Account { if (token !== account.unsubscribeToken) throw new Error("Invalid unsubscribe token."); return { ...account, unsubscribedAt }; }
export function purgeDueDeletions(store: AccountStore, now: string): AccountStore { const cutoff = new Date(now).getTime() - 30 * 86400000; const ids = new Set(store.accounts.filter((account) => account.deletionRequestedAt && new Date(account.deletionRequestedAt).getTime() <= cutoff).map((account) => account.id)); return { ...store, accounts: store.accounts.filter((a) => !ids.has(a.id)), savedAreas: store.savedAreas.filter((a) => !ids.has(a.ownerId)), alertHistory: store.alertHistory.filter((a) => !ids.has(a.ownerId)) }; }
export function purgeOldHistory(store: AccountStore, now: string): AccountStore { const cutoff = new Date(now); cutoff.setUTCMonth(cutoff.getUTCMonth() - 24); return { ...store, alertHistory: store.alertHistory.filter((item) => new Date(item.sentAt).getTime() > cutoff.getTime()) }; }
export function correctionAlerts(history: readonly AlertHistory[], figureId: string, restated: AlertHistory["reported"]): readonly CorrectionAlert[] { return history.filter((item) => item.figureId === figureId && JSON.stringify(item.reported) !== JSON.stringify(restated)).map((item) => ({ ownerId: item.ownerId, figureId, previous: item.reported, restated })); }
export function maySend(store: AccountStore, account: Account): boolean { return !store.killSwitchEnabled && Boolean(account.emailVerifiedAt) && !account.unsubscribedAt; }
export const ALERT_TEMPLATES = { correction: { en: "A figure you were told about has been restated.", fr: "Un chiffre qui vous a été communiqué a été rectifié." } } as const;
export function publicAccountSummary(account: Account): Readonly<{ id: string; locale: string; emailVerified: boolean }> { return { id: account.id, locale: account.locale, emailVerified: Boolean(account.emailVerifiedAt) }; }
