import assert from "node:assert/strict"; import test from "node:test";
import { addSavedArea, ALERT_TEMPLATES, areasForOwner, correctionAlerts, maySend, publicAccountSummary, purgeDueDeletions, purgeOldHistory, requestDeletion, unsubscribeWithToken }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/accounts/policy.ts";
import type { AccountStore } from "../lib/accounts/types";
const reported = { kind: "unknown", evidence: "unknown", reason: { en: "No authoritative public record has been integrated.", fr: "Aucun registre public faisant autorité n’a été intégré." }, coverageGrade: "national-baseline" } as const;
const accounts = [{ id: "a", emailAddress: "example-account-a", passwordHash: "hash", locale: "en", emailVerifiedAt: "2026-01-01", unsubscribeToken: "token-a" }, { id: "b", emailAddress: "example-account-b", passwordHash: "hash", locale: "fr", unsubscribeToken: "token-b" }] as const;
const store: AccountStore = { accounts, savedAreas: [{ id: "area-a", ownerId: "a", geometry: "EXAMPLE", radiusKilometres: 10, alertPreferences: [] }, { id: "area-b", ownerId: "b", geometry: "EXAMPLE", alertPreferences: [] }], alertHistory: [{ id: "h", ownerId: "a", sentAt: "2025-08-11", figureId: "f", reported }], killSwitchEnabled: false };
test("owner isolation and verified bounded saved areas are enforced", () => { assert.deepEqual(areasForOwner(store, "a").map((a) => a.id), ["area-a"]); assert.throws(() => addSavedArea(store, { id: "x", ownerId: "b", geometry: "EXAMPLE", alertPreferences: [] }), /verified/); assert.throws(() => addSavedArea(store, { id: "x", ownerId: "a", geometry: "EXAMPLE", radiusKilometres: 101, alertPreferences: [] }), /bounded/); let full = store; for (let i = 0; i < 24; i += 1) full = addSavedArea(full, { id: `extra-${i}`, ownerId: "a", geometry: "EXAMPLE", alertPreferences: [] }); assert.throws(() => addSavedArea(full, { id: "twenty-six", ownerId: "a", geometry: "EXAMPLE", alertPreferences: [] }), /limit/); });
test("deletion, retention, corrections, unsubscribe, templates, and privacy hold", () => { const deleted = purgeDueDeletions({ ...store, accounts: [requestDeletion(accounts[0], "2026-01-01"), accounts[1]] }, "2026-02-01"); assert.equal(deleted.accounts.some((a) => a.id === "a"), false); const boundary = { ...store, alertHistory: [{ ...store.alertHistory[0]!, sentAt: "2024-03-01T00:00:00Z" }, { ...store.alertHistory[0]!, id: "new", sentAt: "2024-03-01T00:00:01Z" }] }; assert.deepEqual(purgeOldHistory(boundary, "2026-03-01T00:00:00Z").alertHistory.map((item) => item.id), ["new"]); assert.equal(correctionAlerts(store.alertHistory, "f", reported).length, 0); assert.equal(correctionAlerts(store.alertHistory, "f", { ...reported, reason: { en: "Restated.", fr: "Rectifié." } }).length, 1); assert.throws(() => unsubscribeWithToken(accounts[0], "wrong", "2026-01-01"), /Invalid/); assert.equal(maySend(store, unsubscribeWithToken(accounts[0], "token-a", "2026-01-01")), false); assert.ok(ALERT_TEMPLATES.correction.en && ALERT_TEMPLATES.correction.fr); assert.equal(JSON.stringify(ALERT_TEMPLATES).includes("example-account"), false); assert.equal(maySend({ ...store, killSwitchEnabled: true }, accounts[0]), false); const publicJson = JSON.stringify(publicAccountSummary(accounts[0])); assert.equal(publicJson.includes("emailAddress"), false); assert.equal(publicJson.includes("example-account-a"), false); });
