import assert from "node:assert/strict";
import test from "node:test";
import { renderToStaticMarkup } from "react-dom/server";
import { comparisonContext, rankedRidingFixtures }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/comparison/fixtures.ts";
import { RANKING_COPY, comparePlaces, parseRankingSort, rankRidings, rankingContextLines }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/comparison/ranking.ts";
import type { RankedRiding } from "../lib/comparison/types";
import { RankedRidingsTable }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../components/comparison/RankedRidingsTable.tsx";
import { SideBySideComparison }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../components/comparison/SideBySideComparison.tsx";

test("orders only rankable riding rows and keeps the others separate", () => { const result = rankRidings(rankedRidingFixtures); assert.deepEqual(result.ranked.map((row) => row.id), ["r1", "r2"]); assert.deepEqual(result.unranked.map((row) => row.id), ["r3"]); assert.equal(result.ranked[0]?.detectedChangePercent, 4.2); assert.equal(result.ranked[0]?.detectedChangeHectares, 420); assert.equal(result.ranked[0]?.forestedHectares, 10000); assert.equal(result.ranked[0]?.unmatchedSharePercent, 35); assert.equal(result.unranked[0]?.detectedChangeHectares, 80); });
test("ranking sort is share-only and defaults defensively", () => { assert.equal(parseRankingSort("share-asc"), "share-asc"); assert.equal(parseRankingSort("hectares-desc"), "share-desc"); assert.deepEqual(rankRidings(rankedRidingFixtures, "share-asc").ranked.map((row) => row.id), ["r2", "r1"]); });
test("admitted unmatched shares stay within 0–100 percent", () => { for (const row of rankedRidingFixtures) { if (row.unmatchedSharePercent != null) { assert.ok(row.unmatchedSharePercent >= 0 && row.unmatchedSharePercent <= 100); } } });
test("the constant official-matching state is stated once above each table, never in every row", () => { const english = renderToStaticMarkup(<RankedRidingsTable rows={rankedRidingFixtures} context={comparisonContext} locale="en" />); const french = renderToStaticMarkup(<RankedRidingsTable rows={rankedRidingFixtures} context={comparisonContext} locale="fr" />); assert.equal((english.match(/Official matching:/g) ?? []).length, 1); assert.equal((french.match(/Appariement officiel/g) ?? []).length, 1); assert.doesNotMatch(english, /No matching official record|rank-unmatched-share/); assert.doesNotMatch(french, /Sans registre officiel correspondant|rank-unmatched-share/); });
test("incomplete measurements render Unknown in tables and cards", () => { const incomplete = { ...rankedRidingFixtures[0]!, detectedChangePercent: null, detectedChangeHectares: null, measurementCoverage: "partial-with-unknown" as const, sufficientCoverage: false }; const pair = [incomplete, rankedRidingFixtures[1]!] as const; const ranked = renderToStaticMarkup(<RankedRidingsTable rows={pair} context={comparisonContext} locale="en" />); const table = renderToStaticMarkup(<SideBySideComparison places={pair} context={comparisonContext} locale="en" view="table" />); const cards = renderToStaticMarkup(<SideBySideComparison places={pair} context={comparisonContext} locale="fr" />); assert.match(ranked, /<td>Unknown<\/td>/); assert.match(table, /<td>Unknown<\/td>/); assert.match(cards, /Inconnu · Inconnu/); assert.doesNotMatch(`${ranked}${table}${cards}`, />null%|>0%/); });
test("an unranked complete row is never mislabeled as below the forest-area floor", () => { const inconsistent = { ...rankedRidingFixtures[0]!, detectedChangePercent: null, detectedChangeHectares: null, sufficientCoverage: false }; assert.throws(() => renderToStaticMarkup(<RankedRidingsTable rows={[inconsistent]} context={comparisonContext} locale="en" />), /explicit, truthful reason/); });
test("comparison measurements use locale separators and at most two decimals", () => { const precise = { ...rankedRidingFixtures[0]!, detectedChangePercent: 4.234567, detectedChangeHectares: 12345.678, forestedHectares: 10000.5 }; const english = renderToStaticMarkup(<RankedRidingsTable rows={[precise]} context={comparisonContext} locale="en" />); const french = renderToStaticMarkup(<SideBySideComparison places={[precise, rankedRidingFixtures[1]!]} context={comparisonContext} locale="fr" view="table" />); assert.match(english, /<td>4\.23%<\/td><td>12,345\.68 ha<\/td><td>10,000\.5 ha<\/td>/); assert.match(french, /4,23\u00a0%/); assert.match(french, /12\u00a0345,68 ha/); assert.doesNotMatch(`${english}${french}`, /4\.234567|12345\.678/); });
test("context carries bilingual screenshot strings and neutral labels", () => { const copy = `${RANKING_COPY.en.metric} ${RANKING_COPY.fr.metric}`; const strings = rankingContextLines(comparisonContext, "en").join(" "); assert.match(strings, /2000–2024/); assert.match(strings, /Representation Order/); assert.match(strings, /illustrative-1/); assert.equal(/worst|best|top|leader|destruction/i.test(copy), false); });
test("side-by-side accepts exactly two places of the same type", () => { assert.equal(comparePlaces(rankedRidingFixtures.slice(0, 2))[0].id, "r1"); assert.throws(() => comparePlaces([rankedRidingFixtures[0]!]), /exactly two/); assert.throws(() => comparePlaces([{ ...rankedRidingFixtures[0]!, placeType: "reserve" }, rankedRidingFixtures[1]!]), /same type/); });
test("ranked tables have captions and scoped headers for each rendered reason group", () => { const html = renderToStaticMarkup(<RankedRidingsTable rows={rankedRidingFixtures} context={comparisonContext} locale="en" />); assert.match(html, /Satellite observation/); assert.match(html, /Unknown/); assert.equal((html.match(/<caption[ >]/g) ?? []).length, 2); assert.equal((html.match(/scope="col"/g) ?? []).length, 12); assert.match(html, /scope="row"/); assert.match(html, /Complete mapped coverage below 500 forested hectares, not ranked \(1\)/); });
test("the English and French table-query views retain coverage, evidence, shared method notes, and same-route links", () => { const english = renderToStaticMarkup(<SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} context={comparisonContext} locale="en" view="table" />); const french = renderToStaticMarkup(<SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} context={comparisonContext} locale="fr" view="table" />); const englishCards = renderToStaticMarkup(<SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} context={comparisonContext} locale="en" />); const frenchCards = renderToStaticMarkup(<SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} context={comparisonContext} locale="fr" />); assert.match(english, /<table/); assert.match(english, /Coverage/); assert.match(english, /Satellite observation/); assert.match(english, /Method: Rows are ordered by detected change as a share of forested area\./); assert.match(english, /href="\?view=cards"/); assert.match(englishCards, /Method: Rows are ordered by detected change as a share of forested area\./); assert.match(englishCards, /href="\?view=table"/); assert.match(french, /<table/); assert.match(french, /Couverture/); assert.match(french, /Observation satellitaire/); assert.match(french, /Méthode: Les lignes sont ordonnées selon le changement détecté en part de la superficie forestière\./); assert.match(french, /href="\?view=cards"/); assert.match(frenchCards, /Méthode: Les lignes sont ordonnées selon le changement détecté en part de la superficie forestière\./); assert.match(frenchCards, /href="\?view=table"/); });
test("ranking and view links preserve the selected riding pair", () => { const ranking = renderToStaticMarkup(<RankedRidingsTable rows={rankedRidingFixtures} context={comparisonContext} locale="en" sort="share-asc" leftId="r1" rightId="r2" view="table" />); const comparison = renderToStaticMarkup(<SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} context={comparisonContext} locale="en" leftId="r1" rightId="r2" sort="share-asc" />); assert.match(ranking, /href="\?sort=share-desc&amp;left=r1&amp;right=r2&amp;view=table"/); assert.match(comparison, /href="\?view=table&amp;left=r1&amp;right=r2&amp;sort=share-asc"/); });
// @ts-expect-error Ranking accepts ridings only, never reserves.
const reserveRanking: RankedRiding = { ...rankedRidingFixtures[0]!, placeType: "reserve" };
// @ts-expect-error Ranked rows require forestedHectares as the denominator.
const missingDenominator: RankedRiding = { ...rankedRidingFixtures[0]!, forestedHectares: undefined };
// @ts-expect-error Ranked rows require a coverage grade.
const missingCoverage: RankedRiding = { ...rankedRidingFixtures[0]!, coverageGrade: undefined };
// @ts-expect-error Side-by-side comparison requires its method context.
const missingComparisonContext = <SideBySideComparison places={rankedRidingFixtures.slice(0, 2)} locale="en" />;
void reserveRanking; void missingDenominator; void missingCoverage; void missingComparisonContext;
