import assert from "node:assert/strict"; import test from "node:test";
import { aggregateDetectedChange, coverageShares, resolveCoverage }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/coverage/resolve.ts";
import { coverageFixtures }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/coverage/fixtures.ts";
import type { ForestAggregateInput } from "../lib/coverage/types";
test("resolves all provinces and always keeps Quebec north of 52 at national baseline", () => { assert.deepEqual(coverageFixtures.map((item) => resolveCoverage(item).grade), ["enhanced-local-records", "national-baseline-plus-local-context", "extended-record-sparse-official-matching", "national-baseline"]); assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, latitude: 999 }), /Latitude/); assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, year: 1983 }), /Year/); assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, year: new Date().getUTCFullYear() + 1 }), /Year/); assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, periods: [{ startYear: 2020, endYear: 2019, grade: "national-baseline", containsPoint: true }] }), /period/); assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, periods: [{ startYear: 2020, endYear: 2021, grade: "invalid" as never, containsPoint: true }] }), /period/); });
test("aggregation uses forested hectares and preserves edition and range", () => { const result = aggregateDetectedChange({ detectedChangeHectares: 10, forestedHectares: 100, coverageGrade: "national-baseline", boundaryEdition: "edition", timeRange: "2000–2024" }); assert.deepEqual(result, { kind: "figure", value: 10, unit: "%", boundaryEdition: "edition", timeRange: "2000–2024" }); assert.equal(aggregateDetectedChange({ detectedChangeHectares: 0, forestedHectares: 0, coverageGrade: "national-baseline", boundaryEdition: "edition", timeRange: "2000" }).kind, "unknown"); assert.equal(aggregateDetectedChange({ detectedChangeHectares: 0, coverageGrade: "not-applicable", boundaryEdition: "edition", timeRange: "2000" }).kind, "unknown"); assert.equal(aggregateDetectedChange({ detectedChangeHectares: 1, forestedHectares: 100, coverageGrade: "extended-record-sparse-official-matching", boundaryEdition: "edition", timeRange: "2000" }).kind, "unknown"); assert.throws(() => aggregateDetectedChange({ detectedChangeHectares: 101, forestedHectares: 100, coverageGrade: "national-baseline", boundaryEdition: "edition", timeRange: "2000" }), /exceed/); });
test("weighted coverage shares sum to one and corrupt fractions fail", () => { const shares = coverageShares([{ grade: "national-baseline", forestedHectares: 25 }, { grade: "enhanced-local-records", forestedHectares: 75 }]); assert.equal(shares["national-baseline"]! + shares["enhanced-local-records"]!, 1); assert.throws(() => coverageShares([{ grade: "national-baseline", forestedHectares: -1 }]), /non-negative/); });
test("runtime validation rejects unsupported provinces, non-finite hectares, and invalid grades", () => { assert.throws(() => resolveCoverage({ ...coverageFixtures[0]!, province: "XX" as never }), /province/); assert.throws(() => aggregateDetectedChange({ detectedChangeHectares: Number.NaN, forestedHectares: 1, coverageGrade: "national-baseline", boundaryEdition: "edition", timeRange: "2000" }), /Finite/); assert.throws(() => aggregateDetectedChange({ detectedChangeHectares: 1, forestedHectares: Number.POSITIVE_INFINITY, coverageGrade: "national-baseline", boundaryEdition: "edition", timeRange: "2000" }), /Finite/); assert.throws(() => aggregateDetectedChange({ detectedChangeHectares: 1, forestedHectares: 2, coverageGrade: "invalid" as never, boundaryEdition: "edition", timeRange: "2000" }), /registered/); assert.throws(() => coverageShares([{ grade: "national-baseline", forestedHectares: Number.NaN }]), /finite/); assert.throws(() => coverageShares([{ grade: "invalid" as never, forestedHectares: 1 }]), /registered/); });
// @ts-expect-error Land area is never an aggregation input.
const landAreaInput: ForestAggregateInput = { detectedChangeHectares: 1, landAreaHectares: 10, coverageGrade: "national-baseline", boundaryEdition: "x", timeRange: "x" };
void landAreaInput;
