import assert from "node:assert/strict"; import test from "node:test";
import { addRelease, citation, generateCsv, validateArtifact, validateRelease, verifyArtifactContent }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/downloads/generate.ts";
import { exampleRelease }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/downloads/fixtures.ts";
test("example release is bilingual, immutable, and citable", () => { assert.ok(exampleRelease.readme.en && exampleRelease.readme.fr); assert.equal(addRelease([], exampleRelease).length, 1); assert.throws(() => addRelease([exampleRelease], exampleRelease), /immutable/); assert.match(citation(exampleRelease, exampleRelease.artifacts[0]!), /example-boundary/); });
test("csv escapes figures and preserves locale-correct Unknown reasons as blank numeric values", () => { const rows = [{ id: "a,b", reported: { kind: "figure" as const, value: 2, unit: "ha" as const, evidence: "official-record" as const, confidence: { level: "high" as const, ruleId: "CONF-HIGH-001" as const, reason: { en: "x", fr: "y" } }, provenance: { dataset: "x", version: "1", retrievedDate: "x", licence: "ogl-canada-2.0" as const } } }, { id: "u", reported: { kind: "unknown" as const, evidence: "unknown" as const, reason: { en: "No record", fr: "Aucun registre" }, coverageGrade: "national-baseline" as const } }]; const english = generateCsv(rows); const french = generateCsv(rows, "fr"); assert.match(english, /"a,b",2,ha/); assert.match(english, /u,,,No record/); assert.match(french, /u,,,Aucun registre/); assert.equal(/u,0/.test(english), false); assert.equal(/u,0/.test(french), false); });
test("content hashes are verified and metadata contracts reject invalid values", () => { const content = "example bytes"; const artifact = { ...exampleRelease.artifacts[0]!, sha256: "5d27230d2a5f2e71fd9496d567494dc93262f101b4215046e18b0145ef121e41" }; assert.equal(verifyArtifactContent(artifact, content), true); assert.equal(verifyArtifactContent(artifact, "tampered bytes"), false); assert.throws(() => validateArtifact({ ...artifact, url: "https://outside.example/file" }), /unsafe/); assert.throws(() => validateArtifact({ ...artifact, licenceId: "bad" as never }), /licence/); assert.throws(() => validateArtifact({ ...artifact, sha256: "bad" }), /SHA/); assert.throws(() => validateArtifact({ ...artifact, kind: "csv-table", contentType: "application/json" }), /content type/); assert.throws(() => validateArtifact({ ...artifact, retrievedDate: "not-a-date" }), /unsafe/); });
test("release validation rejects missing bilingual readme, duplicate artifacts, and Unknown zero", () => { assert.throws(() => validateRelease({ ...exampleRelease, readme: { en: "", fr: "x" } }), /readme/); assert.throws(() => validateRelease({ ...exampleRelease, artifacts: [exampleRelease.artifacts[0]!, exampleRelease.artifacts[0]!] }), /unique/); assert.throws(() => validateRelease({ ...exampleRelease, readme: { en: "Unknown 0", fr: "Inconnu 0" } }), /Unknown/); assert.throws(() => validateArtifact({ ...exampleRelease.artifacts[0]!, note: { en: "Unknown 0", fr: "Inconnu 0" } }), /Unknown/); });
