import assert from "node:assert/strict"; import test from "node:test"; import { renderToStaticMarkup } from "react-dom/server";
import { ExploreView }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../components/explore/ExploreView.tsx";
import { exploreFixtures }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/explore/fixtures.ts";

test("renders four plan modes, independent same-url controls, fixture boundaries, and native time control", () => { const en = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" />); const listTable = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="recorded-harvest" presentation="list" data="table" />); const fr = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="fr" mode="condition-recovery" presentation="list" data="chart" />); assert.match(en, /Illustrative fixtures only/); assert.match(en, /type="range"/); assert.match(en, /min="1984"/); assert.match(en, /max="2026"/); assert.match(en, /value="2000"/); for (const label of ["Forest change", "Recorded harvest", "Wildfire", "Condition and recovery"]) assert.match(en, new RegExp(label)); assert.match(en, /presentation=map&amp;data=chart/); assert.match(en, /presentation=list&amp;data=chart/); assert.match(en, /presentation=map&amp;data=table/); assert.match(en, /Boundary overlays/); for (const label of ["Watersheds", "Federal ridings", "Provincial ridings", "Reserves", "Treaty areas"]) assert.match(en, new RegExp(label)); assert.match(en, /geometry unavailable/); assert.match(listTable, /aria-label="List"/); assert.match(listTable, /<table/); assert.equal((listTable.match(/scope="col"/g) ?? []).length, 6); assert.match(listTable, /scope="row"/); assert.match(fr, /État et rétablissement/); assert.match(fr, /Exemples illustratifs seulement/); assert.match(fr, /Superpositions de limites/); });
test("map/list and chart/table retain evidence, confidence, coverage, provenance, and Unknown is never zero", () => { const mapChart = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="forest-change" presentation="map" data="chart" />); const listTable = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="condition-recovery" presentation="list" data="table" />); assert.match(mapChart, /aria-label="Map"/); assert.match(mapChart, /aria-label="Chart"/); assert.match(mapChart, /Satellite observation/); assert.match(mapChart, /Source attribution/); assert.match(listTable, /No authoritative public record/); assert.match(listTable, /Coverage/); assert.match(listTable, /Source attribution/); assert.equal(/>0<|caused by|logging|deforestation/i.test(listTable), false); });
test("Explore lazily integrates MapLibre with the PMTiles protocol only on map routes", async () => { const { readFile } = await import("node:fs/promises"); const map = await readFile(new URL("../components/explore/ExploreMapClient.tsx", import.meta.url), "utf8"); const enRoute = await readFile(new URL("../app/en/explore/page.tsx", import.meta.url), "utf8"); const frRoute = await readFile(new URL("../app/fr/explorer/page.tsx", import.meta.url), "utf8"); assert.match(map, /import\("maplibre-gl"\)/); assert.match(map, /import\("pmtiles"\)/); assert.match(map, /addProtocol\("pmtiles"/); assert.match(map, /Verified PMTiles are not yet published/); for (const route of [enRoute, frRoute]) { assert.match(route, /presentation === "map" \? <ExploreMapClient/); assert.match(route, /events=\{events\}/); } });
