import assert from "node:assert/strict"; import test from "node:test"; import { renderToStaticMarkup } from "react-dom/server";
import { ExploreView }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../components/explore/ExploreView.tsx";
import { exploreFixtures }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../lib/explore/fixtures.ts";
test("renders fixture-only map, native time control, symbols, and same-url table in both locales", () => { const en = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="detected-change" />); const allModes = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="detected-change" />); const fr = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="fr" mode="official-harvest" view="table" />); const enTable = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="official-harvest" view="table" />); assert.match(en, /Illustrative fixtures only/); assert.match(en, /type="range"/); assert.match(en, /min="1984"/); assert.match(en, /max="2026"/); assert.match(en, /step="1"/); assert.match(en, /value="2000"/); assert.match(allModes, /<rect/); assert.match(allModes, /<circle/); assert.match(allModes, /<polygon/); assert.match(allModes, /<path/); assert.match(en, /aria-label="Map view"/); assert.equal((en.match(/aria-label="(?:Detected change|Official harvest|Wildfire perimeter|Insect or mortality)"/g) ?? []).length, 4); assert.equal((enTable.match(/scope="col"/g) ?? []).length, 6); assert.match(enTable, /scope="row"/); assert.match(en, /Detected change/); assert.match(fr, /Récolte officielle/); assert.match(en, /view=table/); assert.match(fr, /<table/); assert.match(fr, /Confiance/); assert.match(fr, /Attribution de la source/); assert.match(enTable, /Confidence/); assert.match(enTable, /Source attribution/); assert.match(fr, /Exemples illustratifs seulement/); assert.match(fr, /view=map/); });
test("unknown remains explicit rather than a numeric zero and forbidden causal copy is absent", () => { const html = renderToStaticMarkup(<ExploreView events={exploreFixtures} locale="en" mode="insect-mortality" />); assert.match(html, /No authoritative public record/); assert.equal(/>0<|caused by|logging|deforestation/i.test(html), false); });
