import assert from "node:assert/strict"; import test from "node:test";
// @ts-expect-error explicit extension for Node tests.
import { validateAggregateResult, validateBoundaryEdition, validateForestEvent, validateSourceRecord } from "../lib/records/validate.ts";
const confidence = { level: "high", ruleId: "CONF-HIGH-001", reason: { en: "Example reason", fr: "Raison exemple" } } as const;
const geometry = { crs: "EPSG:4326", original: { type: "Point", coordinates: [-123, 49] }, normalized: { type: "Point", coordinates: [-123, 49] }, areaHectares: 1, positionalConfidenceMetres: 5 } as const;
const source = { status: "example", id: "source", ingestId: "ingest", dataset: "Example", version: "1", licence: "ogl-canada-2.0", retrievedAt: "2026-08-11T00:00:00Z", checksumSha256: "a".repeat(64), sourceUrl: "https://example.local/source" } as const;
const event = { status: "example", id: "event", sourceRecordId: "source", ingestId: "ingest", evidence: "official-record", confidence, geometry, observedFrom: "2024-01-01", observedTo: "2024-12-31", eventDate: "2024-06-01", dateConfidence: "day", lifecycle: "RETIRED", subtype: "recorded-harvest", tenure: "example", forestContext: { definitionVersion: "nfi-1", forestedHectares: 1, referenceYear: 2024 }, display: { en: "Example", fr: "Exemple" }, limitations: { en: "Example limit", fr: "Limite exemple" }, methodVersion: "example-1" } as const;
test("example records meet the normalized contract", () => { validateSourceRecord(source); validateBoundaryEdition({ status: "example", id: "boundary", placeType: "province", effectiveFrom: "2020-01-01", retired: false, geometry }); validateForestEvent(event); validateAggregateResult({ status: "example", id: "aggregate", boundaryEditionId: "boundary", denominator: { hectares: 1, referenceYear: 2024, definitionVersion: "nfi-1" }, timeRange: { from: "2024-01-01", to: "2024-12-31" }, dataVersion: "example-1", coverageGrade: "national-baseline", eventIds: ["event"] }); });
test("contract rejects missing auditability and invalid harvest", () => { assert.throws(() => validateSourceRecord({ ...source, licence: "missing" as never })); assert.throws(() => validateForestEvent({ ...event, lifecycle: "PENDING" })); assert.throws(() => validateForestEvent({ ...event, display: { en: "", fr: "" } })); assert.throws(() => validateAggregateResult({ status: "example", id: "aggregate", boundaryEditionId: "boundary", denominator: { hectares: 1, referenceYear: 2024, definitionVersion: "nfi-1" }, timeRange: { from: "2024-01-01", to: "2024-12-31" }, dataVersion: "example-1", coverageGrade: "national-baseline", eventIds: [] })); });
test("contract rejects example-status, policy, boundary and geometry violations", () => { assert.throws(() => validateSourceRecord({ ...source, retrievedAt: "2026-02-30T00:00:00Z" })); assert.throws(() => validateForestEvent({ ...event, confidence: { ...confidence, ruleId: "CONF-MEDIUM-001" } })); assert.throws(() => validateForestEvent({ ...event, organisation: { name: "Example", role: "holder", date: "2024-01-01", confidence: { ...confidence, ruleId: "CONF-MEDIUM-001" } } })); assert.throws(() => validateForestEvent({ ...event, geometry: { ...geometry, original: { type: "Polygon", coordinates: [[[0, 0], [1, 0], [1, 1], [0, 1]]] } } })); assert.throws(() => validateForestEvent({ ...event, geometry: { ...geometry, original: { type: "MultiPolygon", coordinates: [[[[0, 0], [1, 0], [1, 1], [0, 1]]]] } } })); });
