import { LICENCE_IDS }
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
from "../domain/source-ledger.ts";
// @ts-expect-error -- Node's TypeScript runner requires explicit local extensions.
import { PRODUCT_NAME } from "../domain/brand.ts";
import { createHash } from "node:crypto";
import type { DownloadArtifact, DownloadRelease, DownloadRow } from "./types";
const hasUnknownZero = (value: string) => /(?:unknown|inconnu)\s*(?:value|valeur)?\s*0\b/i.test(value);
const exampleUrl = (value: string) => { try { const url = new URL(value); return url.protocol === "https:" && url.hostname === "example.local"; } catch { return false; } };
const validDate = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
export function validateArtifact(artifact: DownloadArtifact): DownloadArtifact { if (!artifact.id || !artifact.boundaryEdition || !artifact.timeRange || !artifact.methodVersion || !validDate(artifact.retrievedDate) || !artifact.note.en || !artifact.note.fr || !exampleUrl(artifact.url)) throw new Error("Required download metadata is missing or unsafe."); if (!LICENCE_IDS.includes(artifact.licenceId)) throw new Error("Unknown licence."); if (!/^[a-f0-9]{64}$/i.test(artifact.sha256)) throw new Error("SHA-256 is required."); if ((artifact.kind === "csv-table" && artifact.contentType !== "text/csv") || (artifact.kind === "event-record-geopackage-metadata" && artifact.contentType !== "application/geopackage+sqlite3")) throw new Error("Artifact kind and content type must match."); if (hasUnknownZero(artifact.note.en) || hasUnknownZero(artifact.note.fr)) throw new Error("Unknown must not be represented as zero."); return artifact; }
export function validateRelease(release: DownloadRelease): DownloadRelease { if (!release.id.trim() || !release.readme.en.trim() || !release.readme.fr.trim() || release.artifacts.length === 0) throw new Error("A release requires an id, bilingual readme, and artifacts."); if (hasUnknownZero(release.readme.en) || hasUnknownZero(release.readme.fr)) throw new Error("Unknown must not be represented as zero."); const ids = new Set(release.artifacts.map((artifact) => artifact.id)); if (ids.size !== release.artifacts.length) throw new Error("Artifact ids must be unique."); release.artifacts.forEach(validateArtifact); return release; }
export function addRelease(releases: readonly DownloadRelease[], release: DownloadRelease): readonly DownloadRelease[] { if (releases.some((item) => item.id === release.id)) throw new Error("Release ids are immutable."); validateRelease(release); return [...releases, release]; }
export function verifyArtifactContent(artifact: DownloadArtifact, content: Uint8Array | string): boolean { validateArtifact(artifact); return createHash("sha256").update(content).digest("hex") === artifact.sha256.toLowerCase(); }
const escape = (value: string) => /[",\n]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
export function generateCsv(rows: readonly DownloadRow[]): string { return ["id,value,unit,unknown_reason", ...rows.map((row) => row.reported.kind === "figure" ? [row.id, row.reported.value, row.reported.unit, ""].map(String).map(escape).join(",") : [row.id, "", "", row.reported.reason].map(escape).join(","))].join("\n"); }
export function citation(release: DownloadRelease, artifact: DownloadArtifact): string { validateRelease(release); if (!release.artifacts.some((item) => item.id === artifact.id)) throw new Error("Artifact is not part of the release."); return `${PRODUCT_NAME.en}. ${artifact.id}. Release ${release.id}. ${artifact.timeRange}; ${artifact.boundaryEdition}; method ${artifact.methodVersion}; retrieved ${artifact.retrievedDate}. ${artifact.url}`; }
