// @ts-expect-error Node strip-types requires explicit local extensions.
import { EVIDENCE_CLASSES } from "../domain/evidence.ts";
// @ts-expect-error Node strip-types requires explicit local extensions.
import { LICENCE_IDS } from "../domain/source-ledger.ts";
// @ts-expect-error Node strip-types requires explicit local extensions.
import { COVERAGE_GRADES } from "../domain/coverage.ts";
// @ts-expect-error Node strip-types requires explicit local extensions.
import { FOREST_DEFINITION_VERSION } from "../domain/forest.ts";
// @ts-expect-error Node strip-types requires explicit local extensions.
import { PLACE_TYPES } from "../places/types.ts";
import type { AggregateResult, BoundaryEdition, ForestEvent, SourceRecord } from "./types";
const date = (value: string) => /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(`${value}T00:00:00Z`).getTime()) && new Date(`${value}T00:00:00Z`).toISOString().slice(0, 10) === value;
const bilingual = (value: { en: string; fr: string }) => Boolean(value.en.trim() && value.fr.trim());
const finite = (...values: number[]) => values.every(Number.isFinite);
function position(value: unknown): value is [number, number] { return Array.isArray(value) && value.length === 2 && finite(value[0] as number, value[1] as number); }
function coordinates(shape: ForestEvent["geometry"]["original"], crs: string): boolean { const point = (value: unknown) => position(value) && (crs !== "EPSG:4326" || (Math.abs(value[0]) <= 180 && Math.abs(value[1]) <= 90)); const ring = (value: unknown) => Array.isArray(value) && value.length >= 4 && value.every(point) && value[0][0] === value[value.length - 1][0] && value[0][1] === value[value.length - 1][1]; if (shape.type === "Point") return point(shape.coordinates); if (shape.type === "Polygon") return Array.isArray(shape.coordinates) && shape.coordinates.length > 0 && shape.coordinates.every(ring); return shape.type === "MultiPolygon" && Array.isArray(shape.coordinates) && shape.coordinates.length > 0 && shape.coordinates.every((polygon) => Array.isArray(polygon) && polygon.length > 0 && polygon.every(ring)); }
function confidence(value: ForestEvent["confidence"]) { const expected = { high: "CONF-HIGH-001", medium: "CONF-MEDIUM-001", limited: "CONF-LIMITED-001", unknown: "CONF-UNKNOWN-001" } as const; return expected[value.level] === value.ruleId && bilingual(value.reason); }
function geometry(value: ForestEvent["geometry"]) { if (!value || !["EPSG:4326", "EPSG:3347"].includes(value.crs) || !finite(value.areaHectares, value.positionalConfidenceMetres) || value.areaHectares < 0 || value.positionalConfidenceMetres < 0) throw new Error("Geometry requires supported CRS and finite area and positional confidence."); for (const shape of [value.original, value.normalized]) if (!coordinates(shape, value.crs)) throw new Error("Geometry requires valid original and normalized coordinates."); }
export function validateSourceRecord(value: SourceRecord) { const retrieved = new Date(value.retrievedAt); const normalized = value.retrievedAt.includes(".") ? value.retrievedAt : value.retrievedAt.replace("Z", ".000Z"); if (value.status !== "example" || !value.id || !value.ingestId || !value.dataset || !value.version || !LICENCE_IDS.includes(value.licence) || !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{3})?Z$/.test(value.retrievedAt) || Number.isNaN(retrieved.getTime()) || retrieved.toISOString() !== normalized || !/^https:\/\//.test(value.sourceUrl) || !/^[a-f\d]{64}$/i.test(value.checksumSha256)) throw new Error("Source record requires example status, lineage, licence, retrieval, URL and checksum."); return value; }
export function validateBoundaryEdition(value: BoundaryEdition) { if (value.status !== "example" || !value.id || !PLACE_TYPES.includes(value.placeType) || !date(value.effectiveFrom) || (value.effectiveTo && (!date(value.effectiveTo) || value.effectiveTo < value.effectiveFrom)) || (value.retired && !value.effectiveTo) || (!value.retired && value.effectiveTo)) throw new Error("Boundary edition requires example status, valid place type and consistent retirement dates."); geometry(value.geometry); return value; }
export function validateForestEvent(value: ForestEvent) { if (value.status !== "example" || !value.id || !value.sourceRecordId || !value.ingestId || !EVIDENCE_CLASSES.includes(value.evidence) || !confidence(value.confidence) || !["day", "month", "year", "unknown"].includes(value.dateConfidence) || !["ACTIVE", "RETIRED", "PENDING", "UNKNOWN"].includes(value.lifecycle) || !date(value.observedFrom) || !date(value.observedTo) || value.observedTo < value.observedFrom || (value.eventDate && !date(value.eventDate)) || value.forestContext.definitionVersion !== FOREST_DEFINITION_VERSION || !finite(value.forestContext.forestedHectares, value.forestContext.referenceYear) || value.forestContext.forestedHectares < 0 || !value.subtype || !value.tenure || !value.methodVersion || !bilingual(value.display) || !bilingual(value.limitations)) throw new Error("Forest event requires example status, complete policy fields, lineage, time, forest context and bilingual display fields."); geometry(value.geometry); if (value.organisation && (!value.organisation.name || !value.organisation.role || !date(value.organisation.date) || !confidence(value.organisation.confidence))) throw new Error("Organisation role requires name, role, date and valid confidence."); if (value.recovery && !date(value.recovery.observedDate)) throw new Error("Recovery requires observation date."); if (value.subtype === "recorded-harvest" && (value.lifecycle === "PENDING" || (value.lifecycle === "ACTIVE" && !value.corroborated))) throw new Error("Recorded harvest must be RETIRED or corroborated ACTIVE."); return value; }
export function validateAggregateResult(value: AggregateResult) { if (value.status !== "example" || !value.id || !value.boundaryEditionId || !date(value.timeRange.from) || !date(value.timeRange.to) || value.timeRange.to < value.timeRange.from || !value.dataVersion || value.denominator.definitionVersion !== FOREST_DEFINITION_VERSION || !COVERAGE_GRADES.includes(value.coverageGrade) || !finite(value.denominator.hectares, value.denominator.referenceYear) || value.denominator.hectares < 0 || !value.eventIds.length || value.eventIds.some((id) => !id.trim())) throw new Error("Aggregate requires example status, complete denominator, range, version, coverage and auditable event IDs."); return value; }
