import type { CorrectionCase, CorrectionClass, CorrectionNotice } from "./types";
export const SLA: Record<CorrectionClass, Readonly<{ acknowledgementDays: number; resolutionDays: number }>> = { critical: { acknowledgementDays: 1, resolutionDays: 5 }, "indigenous-geography": { acknowledgementDays: 1, resolutionDays: 10 }, material: { acknowledgementDays: 3, resolutionDays: 15 }, minor: { acknowledgementDays: 5, resolutionDays: 30 } };
export function addBusinessDays(date: Date, days: number) { const result = new Date(date); let left = days; while (left) { result.setUTCDate(result.getUTCDate() + 1); if (result.getUTCDay() !== 0 && result.getUTCDay() !== 6) left--; } return result; }
export function dueDates(caseFile: CorrectionCase) { const rule = SLA[caseFile.classification]; return { acknowledgement: addBusinessDays(caseFile.submittedAt, rule.acknowledgementDays), resolution: addBusinessDays(caseFile.submittedAt, rule.resolutionDays) }; }
export function transition(caseFile: CorrectionCase, next: CorrectionCase["status"], at: Date): CorrectionCase { const allowed: Record<CorrectionCase["status"], readonly CorrectionCase["status"][]> = { submitted: ["acknowledged", "rejected"], acknowledged: ["resolved", "rejected"], resolved: [], rejected: [] }; if (!(caseFile.submittedAt instanceof Date) || Number.isNaN(caseFile.submittedAt.getTime()) || !(at instanceof Date) || Number.isNaN(at.getTime())) throw new Error("Correction transition timestamps must be valid dates."); if (at < caseFile.submittedAt) throw new Error("Correction transition cannot precede submission."); if (!allowed[caseFile.status].includes(next)) throw new Error("Invalid correction lifecycle transition."); return { ...caseFile, status: next, ...(next === "acknowledged" ? { acknowledgedAt: at } : {}), ...(next === "resolved" || next === "rejected" ? { resolvedAt: at } : {}) }; }
export function validateCorrection(caseFile: CorrectionCase) { const validDate = (date: Date | undefined) => date instanceof Date && !Number.isNaN(date.getTime()); const validPublicationDate = (value: string) => { if (!/^\d{4}-\d{2}-\d{2}$/.test(value)) return false; const date = new Date(`${value}T00:00:00.000Z`); return !Number.isNaN(date.getTime()) && date.toISOString().slice(0, 10) === value; }; if (!validDate(caseFile.submittedAt) || (caseFile.acknowledgedAt && !validDate(caseFile.acknowledgedAt)) || (caseFile.resolvedAt && !validDate(caseFile.resolvedAt))) throw new Error("Correction timestamps must be valid dates."); if ((caseFile.acknowledgedAt && caseFile.acknowledgedAt < caseFile.submittedAt) || (caseFile.resolvedAt && caseFile.resolvedAt < caseFile.submittedAt) || (caseFile.acknowledgedAt && caseFile.resolvedAt && caseFile.resolvedAt < caseFile.acknowledgedAt)) throw new Error("Correction timestamps must be chronological."); if (!/^\/(?!\/)[^?#]*$/.test(caseFile.priorFigureAddress) || !caseFile.priorFigureAddress.trim()) throw new Error("Prior figure address must be a stable internal app path."); if (caseFile.previouslyNotifiedSubscriberIds.some((id) => !id.trim())) throw new Error("Subscriber identifiers must be nonempty."); if (caseFile.statusKind === "production" && (!caseFile.accountableRecipient?.name.trim() || !caseFile.accountableRecipient.role.trim() || !caseFile.publicRecord)) throw new Error("Production corrections require a named accountable recipient and public record."); if (caseFile.publicRecord && (!caseFile.publicRecord.whatWasWrong.en || !caseFile.publicRecord.whatWasWrong.fr || !caseFile.publicRecord.whatIsNow.en || !caseFile.publicRecord.whatIsNow.fr || !caseFile.publicRecord.whyChanged.en || !caseFile.publicRecord.whyChanged.fr || !validPublicationDate(caseFile.publicRecord.publicationDate))) throw new Error("Public correction records require English and French content and a real ISO publication date."); return caseFile; }
export function evaluateSla(caseFile: CorrectionCase, now: Date) { const due = dueDates(caseFile); if (caseFile.acknowledgedAt && caseFile.acknowledgedAt > due.acknowledgement) return "late-acknowledgement"; if (caseFile.resolvedAt && caseFile.resolvedAt > due.resolution) return "late-resolution"; if (!caseFile.acknowledgedAt && now > due.acknowledgement) return "late-acknowledgement"; if (caseFile.acknowledgedAt && !caseFile.resolvedAt && now > due.resolution) return "late-resolution"; return "on-time"; }
export function correctionNotices(caseFile: CorrectionCase): readonly CorrectionNotice[] { if (!caseFile.publicRecord) return []; return caseFile.previouslyNotifiedSubscriberIds.map((subscriberId) => ({ caseId: caseFile.id, subscriberId, publicationDate: caseFile.publicRecord!.publicationDate })); }
export function isAttributionDispute(classification: CorrectionClass) { return classification === "indigenous-geography"; }
