import { FOREST_DEFINITION } from "./forest";
import { localized, type LocalizedString } from "./localized";

export type GlossaryEntry = Readonly<{
  id: string;
  term: LocalizedString;
  definition: LocalizedString;
}>;

export const GLOSSARY: readonly GlossaryEntry[] = Object.freeze([
  { id: "forest", term: localized("Forest", "Forêt"), definition: localized(`${FOREST_DEFINITION.text.en} For a future production calculation, the denominator will use an admitted NTEMS forest mask for the first year of the requested range. Current results are illustrative.`, `${FOREST_DEFINITION.text.fr} Pour un futur calcul de production, le dénominateur utilisera un masque forestier NTEMS admis pour la première année de la période demandée. Les résultats actuels sont illustratifs.`) },
  { id: "detected-change", term: localized("Detected change", "Changement détecté"), definition: localized("A reduction in tree cover seen in satellite imagery between two years. It does not say what caused the change.", "Réduction du couvert arboré observée dans des images satellitaires entre deux années. Elle n’indique pas la cause du changement.") },
  { id: "recorded-harvest", term: localized("Recorded harvest", "Récolte consignée"), definition: localized("An official provincial record showing that trees were cut at this location.", "Registre provincial officiel indiquant que des arbres ont été coupés à cet emplacement.") },
  { id: "cutblock", term: localized("Cutblock", "Parterre de coupe"), definition: localized("An area a province has recorded for harvesting. A recorded cutblock is not always a harvested cutblock; its lifecycle status must be checked.", "Zone qu’une province a consignée aux fins de récolte. Un parterre de coupe consigné n’est pas toujours récolté; son état de cycle de vie doit être vérifié.") },
  { id: "fire-perimeter", term: localized("Fire perimeter", "Périmètre d’incendie"), definition: localized("The outer boundary reported by an agency for a fire. It is not a damage map, and unburned patches may exist inside it.", "Limite extérieure déclarée par un organisme pour un incendie. Il ne s’agit pas d’une carte des dommages, et des zones non brûlées peuvent s’y trouver.") },
  { id: "salvage-harvest", term: localized("Salvage harvest", "Coupe de récupération"), definition: localized("Cutting trees already killed by fire or insects. In satellite data it can resemble other harvest.", "Coupe d’arbres déjà tués par le feu ou les insectes. Dans les données satellitaires, elle peut ressembler à une autre récolte.") },
  { id: "evidence-class", term: localized("Evidence class", "Classe de preuve"), definition: localized("One of four labels required on every claim: official record, satellite observation, derived estimate, or unknown.", "Une des quatre étiquettes exigées pour chaque affirmation : registre officiel, observation satellitaire, estimation dérivée ou inconnu.") },
  { id: "coverage-grade", term: localized("Coverage grade", "Niveau de couverture"), definition: localized("How much detailed record the product holds for a mapped area and time. Coverage can vary inside a province.", "Quantité de renseignements détaillés que le produit détient pour une zone cartographiée et une période. La couverture peut varier à l’intérieur d’une province.") },
  { id: "denominator", term: localized("Denominator", "Dénominateur"), definition: localized("The forested hectares by which a percentage is divided. It is always stated with the number and uses the first year of the requested range.", "Hectares forestiers par lesquels un pourcentage est divisé. Il est toujours indiqué avec la valeur et utilise la première année de la période demandée.") },
  { id: "unmatched-change", term: localized("Unmatched change", "Changement sans correspondance"), definition: localized("Detected change for which no authoritative record has been integrated for the location. It does not establish legality, reporting status, documentation status, or cause.", "Changement détecté pour lequel aucun registre faisant autorité n’a été intégré pour l’emplacement. Il n’établit ni la légalité, ni l’état de déclaration ou de documentation, ni la cause.") },
  { id: "boundary-edition", term: localized("Boundary edition", "Édition de limite"), definition: localized("The version of a boundary used for a calculation. Ridings and other boundaries change over time.", "Version d’une limite utilisée pour un calcul. Les circonscriptions et d’autres limites changent au fil du temps.") },
  { id: "ntems", term: localized("NTEMS", "NTEMS"), definition: localized("The National Terrestrial Ecosystem Monitoring System: annual satellite mapping of Canadian forests from 1984, produced by the Canadian Forest Service with the University of British Columbia.", "Le Système national de surveillance des écosystèmes terrestres : cartographie satellitaire annuelle des forêts canadiennes depuis 1984, produite par le Service canadien des forêts avec l’Université de la Colombie-Britannique.") },
  { id: "recovery-indicated", term: localized("Recovery indicated", "Rétablissement indiqué"), definition: localized("Later imagery shows increasing canopy. This is not the same as recovered forest structure, species mix, or habitat value.", "Des images ultérieures montrent une augmentation du couvert. Cela n’équivaut pas au rétablissement de la structure forestière, du mélange d’espèces ou de la valeur de l’habitat.") },
  { id: "method-version", term: localized("Method version", "Version de méthode"), definition: localized("The recorded version of the rules used to produce a number. If the rules change, affected numbers are recomputed and the change is published.", "Version consignée des règles utilisées pour produire une valeur. Si les règles changent, les valeurs touchées sont recalculées et le changement est publié.") },
]);
