#!/bin/zsh
# Owner-local remediation for only the two exact, existing derived manifests.
set -euo pipefail
umask 077
source "${0:A:h}/aws-direct-mfa-role-session.sh"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CHECKER="$SCRIPT_DIR/check-wildfire-derived-manifest-retention.mjs"
DATA_ROOT="${WITNESS_TREE_DATA_ROOT:-/Volumes/Extended_SSD/Witness_Tree-data}"
PROFILE="WitnessTreeArchiveOperator" ROLE="WitnessTreeWildfireDerivedPromotionUploader" ACCOUNT="286853118812" REGION="ca-central-1" BUCKET="witness-tree-raw-archive-ca-central-1" RETAIN_UNTIL="2033-08-12T00:00:00Z"
BC_PAYLOAD="derived/bc-wildfire/bc-wildfire-geometry-policy-v1-2026-08-14/2026-08-14T20-31-39Z/8ee36cc6bdfb5ef267340537e4cf822df7cc886873c7fcf65a1b2b12006d34ce/payload/bc-wildfire-216-feature-release.gpkg"
BC_MANIFEST="derived/bc-wildfire/bc-wildfire-geometry-policy-v1-2026-08-14/2026-08-14T20-31-39Z/8ee36cc6bdfb5ef267340537e4cf822df7cc886873c7fcf65a1b2b12006d34ce/manifest.json"
ON_PAYLOAD="derived/on-fire-disturbance/ontario-in-year-fire-geometry-policy-v1-2026-08-14/2026-08-14T13-49-36Z/5e55c5d47559c350d9b31ffeda6bd39cfce64a3c57169098fff66341cd8ead31/payload/ontario-in-year-fire-perimeters-188-feature-derived.gpkg"
ON_MANIFEST="derived/on-fire-disturbance/ontario-in-year-fire-geometry-policy-v1-2026-08-14/2026-08-14T13-49-36Z/5e55c5d47559c350d9b31ffeda6bd39cfce64a3c57169098fff66341cd8ead31/manifest.json"
[[ $# -eq 3 && ( "$1" == "--preflight" || "$1" == "--run" ) ]] || { print -u2 -- "Usage: $0 --preflight|--run /absolute/owner-approval.json /absolute/evidence.json"; exit 64; }
MODE="$1" APPROVAL="$2" EVIDENCE="$3"
fail() { print -u2 -- "Stopped: $1"; exit "${2:-65}"; }
[[ "$APPROVAL" == /* && "$EVIDENCE" == /* && -d "$DATA_ROOT" && "$DATA_ROOT" == /* ]] || fail "Paths must be absolute and the data root must exist; no TOTP or AWS call was made"
[[ -f "$APPROVAL" && -O "$APPROVAL" && "$(stat -f %Lp "$APPROVAL" 2>/dev/null)" == 600 ]] || fail "Approval must be owner-owned mode 600; no TOTP or AWS call was made"
[[ ! -e "$EVIDENCE" ]] || fail "Evidence path already exists; refusing overwrite"
TMP="$(mktemp -d /private/tmp/witness-tree-derived-manifest-retention.XXXXXX)"; chmod 700 "$TMP"; trap 'unset AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_SESSION_TOKEN totp mfa_serial; rm -rf "$TMP"' EXIT
node "$CHECKER" --preflight "$APPROVAL" "$DATA_ROOT" > /dev/null || fail "Approval or local artifacts failed closed; no TOTP or AWS call was made"
if [[ "$MODE" == "--preflight" ]]; then print -- "PRECHECK passed: only the two exact manifest versions may receive COMPLIANCE retention; no TOTP or AWS call was made."; exit 0; fi
wt_assume_direct_mfa_role "$PROFILE" "$ACCOUNT" "$ROLE" witness-tree-derived-manifest-retention > "$TMP/session.json"
export AWS_ACCESS_KEY_ID="$(jq -er '.Credentials.AccessKeyId' "$TMP/session.json")" AWS_SECRET_ACCESS_KEY="$(jq -er '.Credentials.SecretAccessKey' "$TMP/session.json")" AWS_SESSION_TOKEN="$(jq -er '.Credentials.SessionToken' "$TMP/session.json")"
[[ "$(aws sts get-caller-identity --query Account --output text)" == "$ACCOUNT" ]] || fail "Assumed role is outside the approved account"
head_exact() { local name="$1" key="$2"; aws s3api head-object --bucket "$BUCKET" --key "$key" --checksum-mode ENABLED --region "$REGION" --output json > "$TMP/$name.latest.json" || fail "Exact current head failed" 70; node "$CHECKER" --validate-head "$TMP/$name.latest.json" "$name" > /dev/null || fail "Exact current head drifted" 70; local version="$(jq -er '.VersionId' "$TMP/$name.latest.json")"; aws s3api head-object --bucket "$BUCKET" --key "$key" --version-id "$version" --checksum-mode ENABLED --region "$REGION" --output json > "$TMP/$name.json" || fail "Exact versioned head failed" 70; node "$CHECKER" --validate-head "$TMP/$name.json" "$name" > /dev/null || fail "Exact versioned head drifted" 70; [[ "$version" == "$(jq -er '.VersionId' "$TMP/$name.json")" ]] || fail "Current version changed during exact head" 70; }
head_exact bcPayload "$BC_PAYLOAD"; head_exact bcManifest "$BC_MANIFEST"; head_exact ontarioPayload "$ON_PAYLOAD"; head_exact ontarioManifest "$ON_MANIFEST"
for pair in "bcManifest:$BC_MANIFEST" "ontarioManifest:$ON_MANIFEST"; do name="${pair%%:*}"; key="${pair#*:}"; version="$(jq -er '.VersionId' "$TMP/$name.json")"; if aws s3api get-object-retention --bucket "$BUCKET" --key "$key" --version-id "$version" --region "$REGION" --output json > "$TMP/$name.before.json" 2> "$TMP/$name.before.err"; then fail "Manifest already has retention; refusing any retention mutation" 70; elif ! grep -Eq 'NoSuchObjectLockConfiguration|NoSuchObjectLockConfigurationException' "$TMP/$name.before.err"; then fail "Manifest retention state is ambiguous; refusing mutation" 70; fi; current="$(aws s3api head-object --bucket "$BUCKET" --key "$key" --checksum-mode ENABLED --region "$REGION" --query VersionId --output text)"; [[ "$current" == "$version" ]] || fail "Manifest current version changed; refusing mutation" 70; aws s3api put-object-retention --bucket "$BUCKET" --key "$key" --version-id "$version" --retention "Mode=COMPLIANCE,RetainUntilDate=$RETAIN_UNTIL" --region "$REGION" --output json > "$TMP/$name.put.json" || fail "Manifest retention write failed" 70; aws s3api get-object-retention --bucket "$BUCKET" --key "$key" --version-id "$version" --region "$REGION" --output json > "$TMP/$name.retention.json" || fail "Manifest retention readback failed" 70; node "$CHECKER" --validate-retention "$TMP/$name.retention.json" "$name" > /dev/null || fail "Manifest retention readback drifted" 70; done
for pair in "bcPayload:$BC_PAYLOAD" "ontarioPayload:$ON_PAYLOAD"; do name="${pair%%:*}"; key="${pair#*:}"; version="$(jq -er '.VersionId' "$TMP/$name.json")"; aws s3api get-object-retention --bucket "$BUCKET" --key "$key" --version-id "$version" --region "$REGION" --output json > "$TMP/$name.retention.json" || fail "Payload retention readback failed" 70; node "$CHECKER" --validate-retention "$TMP/$name.retention.json" "$name" > /dev/null || fail "Payload retention readback drifted" 70; done
node "$CHECKER" --write-evidence "$APPROVAL" "$TMP/bcPayload.json" "$TMP/bcManifest.json" "$TMP/ontarioPayload.json" "$TMP/ontarioManifest.json" "$TMP/bcPayload.retention.json" "$TMP/bcManifest.retention.json" "$TMP/ontarioPayload.retention.json" "$TMP/ontarioManifest.retention.json" "$EVIDENCE" > /dev/null || fail "Evidence validation failed"
print -- "Derived wildfire manifest retention completed for only the two exact manifest versions; redacted owner-only evidence written."
