import { OfficialPublishedHarvestComparison } from "witness-tree";

// Every row below is lifted verbatim from
// data/phase2-official-published-harvest-comparison.json, the artifact the two
// real routes pass straight through. The reference values are Statistics
// Canada Table 2.10 square kilometres converted nominally to hectares, so a
// fabricated figure here would misstate a published official source.

// A cross-province slice of the computed rows, chosen so that all three
// Statistics Canada source flags appear (agency estimate, revised,
// preliminary) alongside unflagged rows and the restricted later years.
const ROWS = [
  {
    province: "BC",
    fromYear: 1990,
    toYear: 1991,
    witnessTreeObservedForestLossHectares: 329680.567893,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 193700,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: false, revised: false, agencyEstimated: true },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 135980.567893,
    withholdReason: null,
  },
  {
    province: "BC",
    fromYear: 1996,
    toYear: 1997,
    witnessTreeObservedForestLossHectares: 290614.840202,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 173800,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: false, revised: true, agencyEstimated: false },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 116814.840202,
    withholdReason: null,
  },
  {
    province: "BC",
    fromYear: 2013,
    toYear: 2014,
    witnessTreeObservedForestLossHectares: 504246.748868,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 167200,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: false, revised: false, agencyEstimated: false },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 337046.748868,
    withholdReason: null,
  },
  {
    province: "AB",
    fromYear: 2014,
    toYear: 2015,
    witnessTreeObservedForestLossHectares: 750652.497706,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 96500,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: true, revised: false, agencyEstimated: false },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 654152.497706,
    withholdReason: null,
  },
  {
    province: "ON",
    fromYear: 1996,
    toYear: 1997,
    witnessTreeObservedForestLossHectares: 297797.591564,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 209300,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: false, revised: true, agencyEstimated: false },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 88497.591564,
    withholdReason: null,
  },
  {
    province: "QC",
    fromYear: 2014,
    toYear: 2015,
    witnessTreeObservedForestLossHectares: 497571.571841,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: 202100,
    referenceRoundingHalfWidthHectares: 50,
    referenceSourceFlags: { preliminary: false, revised: false, agencyEstimated: true },
    comparisonStatus: "computed-rounded-reference",
    nominalSignedDifferenceHectares: 295471.571841,
    withholdReason: null,
  },
  {
    province: "BC",
    fromYear: 2015,
    toYear: 2016,
    witnessTreeObservedForestLossHectares: 380656.677017,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "AB",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 541967.81379,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "QC",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 518905.596375,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
] as const;

// The complete set of 14 later reference values withheld under the source
// repository's personal-use, all-rights-reserved terms. They are the reason
// the page has an unknown state at all: unknown, never zero.
const WITHHELD = [
  {
    province: "BC",
    fromYear: 2015,
    toYear: 2016,
    witnessTreeObservedForestLossHectares: 380656.677017,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "BC",
    fromYear: 2016,
    toYear: 2017,
    witnessTreeObservedForestLossHectares: 595549.084647,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "BC",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 655074.292949,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "BC",
    fromYear: 2018,
    toYear: 2019,
    witnessTreeObservedForestLossHectares: 777928.019284,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "AB",
    fromYear: 2015,
    toYear: 2016,
    witnessTreeObservedForestLossHectares: 582395.310307,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "AB",
    fromYear: 2016,
    toYear: 2017,
    witnessTreeObservedForestLossHectares: 734413.551114,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "AB",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 541967.81379,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "AB",
    fromYear: 2018,
    toYear: 2019,
    witnessTreeObservedForestLossHectares: 684053.104796,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "ON",
    fromYear: 2015,
    toYear: 2016,
    witnessTreeObservedForestLossHectares: 226940.966064,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "ON",
    fromYear: 2016,
    toYear: 2017,
    witnessTreeObservedForestLossHectares: 250246.833054,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "ON",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 316334.602269,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "QC",
    fromYear: 2015,
    toYear: 2016,
    witnessTreeObservedForestLossHectares: 571315.530985,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "QC",
    fromYear: 2016,
    toYear: 2017,
    witnessTreeObservedForestLossHectares: 657379.278642,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
  {
    province: "QC",
    fromYear: 2017,
    toYear: 2018,
    witnessTreeObservedForestLossHectares: 518905.596375,
    strictNfdExactTotalHectares: null,
    referenceHectaresNominal: null,
    referenceRoundingHalfWidthHectares: null,
    referenceSourceFlags: null,
    comparisonStatus: "pending-restricted-source",
    nominalSignedDifferenceHectares: null,
    withholdReason: "The later reference source is restricted to personal use and states all rights reserved. Its numeric value is not included in this public artifact.",
  },
] as const;

export const AllProvinces = () => (
  <OfficialPublishedHarvestComparison rows={[...ROWS]} locale="en" />
);

export const BritishColumbia = () => (
  <OfficialPublishedHarvestComparison rows={[...ROWS]} locale="en" province="BC" />
);

export const WithheldReferenceValues = () => (
  <OfficialPublishedHarvestComparison rows={[...WITHHELD]} locale="en" />
);

export const French = () => (
  <OfficialPublishedHarvestComparison rows={[...ROWS]} locale="fr" />
);
